services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: stockify-postgres
    environment:
      POSTGRES_DB: stockify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stockify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - stockify-network
  # Spring Boot Application
  stockify-app:
    build: .
    container_name: stockify-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=10000
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
      - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=false
    ports:
      - "10000:10000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10000/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - stockify-network

networks:
  stockify-network:
    driver: bridge

volumes:
  postgres_data:
    name: stockify-postgres-data