services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: stockify-postgres
    environment:
      POSTGRES_DB: stockify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stockify"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped  # Spring Boot Application
  stockify-app:
    build: .
    container_name: stockify-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    name: stockify-postgres-data
