version: '3.8'
services:
  db:
    image: postgres:15
    container_name: etsy_postgres
    environment:
      POSTGRES_DB: etsystoktakip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: etsy_stoktakip_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/etsystoktakip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    restart: always

volumes:  
  pgdata:
