version: '3.8'
services:
  postgres-prod:
    image: postgres:16-alpine
    container_name: stockify-postgres-prod
    environment:
      POSTGRES_DB: stockify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  stockify-app:
    build: .
    container_name: stockify-app
    depends_on:
      postgres-prod:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_URL=jdbc:postgresql://postgres-prod:5432/stockify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_prod_data:
    name: stockify-postgres-prod-data
